### ISSUE TITLE
Alta de Tarifa por proveedor

### ISSUE THREAD

**Issue by sposzalski** [nicolasgarfinkiel/PlanificacionMedios#1]
Al dar de alta una tarifa por proveedor pide que la misma este anteriormente carga y vigente.
Debería crear la tarifa para todos los Vehículos y asociarle el importe.

**Comment by pablozabo** [comment]
debería cargar el tarifario siempre y cuando no exista uno vigente.

**Comment by pablozabo** [comment]
y qué rango de fechas le asignamos?

**Comment by pablozabo** [comment]
mira que no tengo todo el dia para vos, eh.

**Comment by sposzalski** [comment]
Close

**Comment by sposzalski** [comment]
pone dos controles para las fechas.

**Comment by pablozabo** [comment]
Ok. Pero solo se van a utilizar si no existe el tarifario.

Ahora que lo pienso puede ser algo confuso porque ese mismo rango de fechas puede solapar a uno ya existente en un vehiculo en particular. Entonces la app va a tirar error de validación. El problema es que si un proveedor tiene asignado mas de un vehiculo, el usuario va a putear.

Enviado desde mi teléfono con Windows 10

De: sposzalski<mailto:notifications@github.com>
Enviado: miércoles, 23 de agosto de 2017 5:55 p. m.
Para: nicolasgarfinkiel/PlanificacionMedios<mailto:PlanificacionMedios@noreply.github.com>
CC: pablozabo<mailto:pablozabo@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [nicolasgarfinkiel/PlanificacionMedios] Alta de Tarifa por proveedor (#1)


pone dos controles para las fechas.

**Comment by pablozabo** [comment]
este ya esta listo.
