### ISSUE TITLE
Tarifario

### ISSUE THREAD

**Issue by sposzalski** [nicolasgarfinkiel/PlanificacionMedios#4]
1. Agregar la baja de un Tarifario, **SOLO PUEDE DAR LA BAJA EL ROL QUE AUTORIZA**
2. Agregar en la creación de un tarifario un upload (Contrato)
3. Agregar un input mas de Numero Proveedor SAP

**Comment by pablozabo** [comment]
@sposzalski :
 
1-qué tipo de archivo es el del punto 2?.
2-como hacemos con el punto 2 si el tarifario se da de alta desde proveedor?.

**Comment by pablozabo** [comment]
En el punto 1, actualmente los tarifarios se cierran, no se dan de baja y se utilizan para poder obtener la fecha desde de un nuevo tarifario. El usuario NO ingresa manualmente la fecha desde.

**Comment by sposzalski** [comment]
1.- PDF
2.- Ese pdf se asocia a cada tarifario. Es el contrato con el medio, por ejemplo Artear.

**Comment by sposzalski** [comment]
3.- Ya lo hablamos por mail.

**Comment by pablozabo** [comment]
2- pero se va a repetir el mismo pdf a todos los tarifarios involucrados.

**Comment by sposzalski** [comment]
Si es correcto.
