### ISSUE TITLE
Tarifa

### ISSUE THREAD

**Issue by sposzalski** [nicolasgarfinkiel/PlanificacionMedios#9]
En la tarifa luego de ingresar los importe pasa automáticamente a pendiente aprobación.

debe haber un estado intermedio y luego el usuario enviarlo a aprobar.

**Comment by pablozabo** [comment]
actualmente un tarifario pasa a pendiente de aprobación si todas las tarifas que lo componen tienen importe asignado. 
Luego, se habilita en boton 'Aprobar' en la grilla de tarifarios.


Veo que no estas al tanto, esta todo hecho.

**Comment by sposzalski** [comment]
Pero yo puedo completar todo sin querer enviarlo a aprobar.
No obstante dejalo así.
Recorda que se envía a FC una vez aprobado. Hiciste ese cambio?
